spring:
  main:
    lazy-initialization: true
    log-startup-info: true
  devtools:
    add-properties: false
    remote:
      restart:
        enabled: false

  datasource:
    url: jdbc:postgresql://croakorder.c5ois6mg04qk.ap-southeast-1.rds.amazonaws.com:5432/croakorder
    username: postgres
    password: croakorder
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 45MB
      enabled: true
---
server:
  port: 8080
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always
---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: chuvuz04112001@gmail.com
    password: tziahhlnkeevrsvj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
aws:
  bucket:
    name: croak-order-g1-sep490
  region: ap-southeast-1
  accessKey: AKIA47CR3W7WTLBHUJXW
  secretKey: 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

logging:
  level:
    web: WARN
    org:
      springframework:
        boot:
          autoconfigure: WARN
