spring:
  main:
    lazy-initialization: true
    log-startup-info: true
  devtools:
    add-properties: false
    remote:
      restart:
        enabled: false

  datasource:
    url: jdbc:postgresql://public-vultr-prod-ba6a796c-a712-4072-b9a7-6c1e1a129699-vultr-pr.vultrdb.com:16751/croak-g1
    username: vultradmin
    password: AVNS_z8b_xDvkX7bCsumLEQR
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 45MB
      enabled: true
---
server:
  port: 8080
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always
---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: chuvuz04112001@gmail.com
    password: tziahhlnkeevrsvj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
aws:
  bucket:
    name: rentease
  region: ap-southeast-2
  accessKey: AKIA6ODU6VDQE6V2VFIR
  secretKey: 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

logging:
  level:
    web: WARN
    org:
      springframework:
        boot:
          autoconfigure: WARN
