spring:
  main:
    lazy-initialization: true
    log-startup-info: true
  devtools:
    add-properties: false
    remote:
      restart:
        enabled: false

  datasource:
    url: jdbc:postgresql://sep490-co.cpaq8iy8010w.ap-southeast-1.rds.amazonaws.com:5432/sep490-co
    username: postgres
    password: sep490-co
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 45MB
      enabled: true
---
server:
  port: 8080
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always
---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: chuvuz04112001@gmail.com
    password: tziahhlnkeevrsvj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
aws:
  bucket:
    name: croak-order-2024
  region: ap-southeast-1
  accessKey: AKIAQEFWAHL2N262OVLQ
  secretKey: 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

logging:
  level:
    web: WARN
    org:
      springframework:
        boot:
          autoconfigure: WARN
