spring:
  main:
    lazy-initialization: true
    log-startup-info: true
  devtools:
    add-properties: false
    remote:
      restart:
        enabled: false

  datasource:
    url: jdbc:postgresql://dblink
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
---
server:
  port: 8080
  error:
    include-stacktrace: always
    include-exception: true
    include-message: always
---
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: xxx@gmail.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
aws:
  bucket:
    name: xxx
    accessKey: AKIAQ3EGQNBOLSXAQLEQxxx
    secretKey: 02rjNAgcGATaudQMGeaO0xMdS6AB0OYP1+hmJf/Fxxx

logging:
  level:
    web: WARN
    org:
      springframework:
        boot:
          autoconfigure: WARN